Harryb/set semantics
awslabs/smithy-rs pull request #1446
Opened 2022-06-07 17:01 UTC by hlbarber

## Motivation and Context

- The semantics of [set](https://awslabs.github.io/smithy/1.0/spec/core/model.html#set) requires insertion ordering, however the Rust [HashSet](https://doc.rust-lang.org/std/collections/struct.HashSet.html) is not ordered. We are currently backing `set` with a `std::vec::Vec`, however this does not prevent duplicates.
- Fixes https://github.com/awslabs/smithy-rs/issues/972
- Closes https://github.com/awslabs/smithy-rs/issues/44 

## Description

- Add a insertion ordered non-repeating collection `Set<T>` to `aws-smithy-types`
- Integrate `Set<T>` into smithy codegen

## Checklist

- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

2022-06-08 17:11 UTC, hlbarber commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/rustlang/RustTypes.kt
> +            fun RuntimeType(runtimeConfig: RuntimeConfig): RuntimeType {
We've promoted this from a `val` to a function in order to accommodate the need for a `dependency`.

2022-06-08 17:11 UTC, hlbarber commented on codegen/src/test/kotlin/software/amazon/smithy/rust/lang/RustWriterTest.kt
> +                    "Set" to RuntimeType.Set(TestRuntimeConfig)
These tests have been "modernized" (using `TestWorkspace.testProject()`) in order to allow for dependency injection here.

2022-06-08 17:11 UTC, hlbarber commented on codegen/src/test/kotlin/software/amazon/smithy/rust/lang/RustWriterTest.kt
> +            it.rustBlock("fn inner()") {
We cannot do this within `unitTest` because it takes a `string` rather than provide a writer.

2022-06-09 14:10 UTC, rcoh requested changes
overall I love the direction! And thanks for modernizing some tests :-)

I think we can completely remove the differential behavior for Vec and Set with a couple of ideas I mentioned in a comment above:

1. Use `symbolProvider.toSymbol()` instead of `Vec` to get the type of the collection
2. Add a `push` method to `Set`

Thanks for addressing this extremely long standing issue!

(And hopefully someone already told you about "debug mode" codegen which makes tracking down where code is coming from much easier)

2022-06-09 14:10 UTC, rcoh commented on codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpBoundProtocolGenerator.kt
> +                val collection = if (model.expectShape(it.member.target) is SetShape) {
yeah—you can change them to:
```rust
val collectionType = symbolProvider.toSymbol(model.expectShape(it.member.target))
val memberName = symbolProvider.toMemberName(it.member)
rustTemplate("let mut $memberName = #{collection}::new();, "Collection" to collectionType)
```
(or similar)

2022-06-09 14:10 UTC, rcoh commented on codegen-server/src/main/kotlin/software/amazon/smithy/rust/codegen/server/smithy/protocols/ServerHttpBoundProtocolGenerator.kt
> +                            "insert"
since we own `Set` why don't we add a push method for convenience? you can make it `#[doc(hidden)]` if you want

2022-06-09 14:10 UTC, rcoh commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/rustlang/RustTypes.kt
> +            }
for slightly cleaner code:
`CargoDependency.SmithyTypes(runtimeConfig).asType().member("aws_smithy_types::Set")`

2022-06-09 14:10 UTC, rcoh commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/protocols/parse/JsonParserGenerator.kt
> +                    }
we don't need this—just use `symbolProvider.toSymbol(shape)`

2022-06-09 14:10 UTC, rcoh commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/SymbolVisitor.kt
> -        }
let's a comment that justifies why this is OK—when this code was written, sets could contain floats but that was changed:

> A set shape requires a single member named member, and the member MUST target either a string, blob, byte, short, integer, long, bigInteger, or bigDecimal shape. The targeted shape MUST NOT be marked with the [streaming trait](https://awslabs.github.io/smithy/1.0/spec/core/stream-traits.html#streaming-trait).

2022-06-09 14:10 UTC, rcoh commented on rust-runtime/aws-smithy-types/src/lib.rs
> +pub use crate::set::*;
especially with `pub use`, lets enumerate these for clarity

2022-06-09 18:44 UTC, hlbarber commented on codegen/src/test/kotlin/software/amazon/smithy/rust/lang/RustWriterTest.kt
> +            it.rustBlock("fn inner()") {
https://github.com/awslabs/smithy-rs/pull/1450 addresses this

2022-06-13 14:26 UTC, rcoh reviewed
looking good so far!

2022-06-13 14:26 UTC, rcoh commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/generators/BuilderGenerator.kt
> +        docs("To override the contents of this collection use [`${member.setterName()}`](Self::${member.setterName()}).")
might as well have some custom docs that call out the deduplication

2022-06-13 14:26 UTC, rcoh commented on codegen/src/main/kotlin/software/amazon/smithy/rust/codegen/smithy/protocols/parse/JsonParserGenerator.kt
> +                                        }
do we want to error here? or just deduplicate?

2022-06-13 14:26 UTC, rcoh commented on CHANGELOG.next.toml
> +author = "hlbarber"
we'll need to call out the exact breaking change and provide upgrade instructions

2022-06-14 16:48 UTC, hlbarber commented on codegen/src/test/kotlin/software/amazon/smithy/rust/lang/RustWriterTest.kt
> +            it.rustBlock("fn inner()") {
Fixed https://github.com/awslabs/smithy-rs/pull/1446/commits/b8c70b83bb0dd26554303b99888768109a68d44d

2022-08-02 17:53 UTC, hlbarber commented
Closing this due to https://github.com/awslabs/smithy/pull/1278

2022-08-02 17:53 UTC, closed without merging