SERVER_CHANGELOG.md has been added for v0.44.0
awslabs/smithy-rs pull request #1500
Opened 2022-06-27 14:11 UTC by drganjoo

## Motivation and Context
SERVER_CHANGELOG.md  has been added (generated through the changelogger tool)

## Description
Server side SDK has it's own SERVER_CHANGELOG.md that will have the server side changes carried out in a revision.

## Testing

## Checklist

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-27 16:46 UTC, jdisanti commented
Let's talk about how we should go about this. My initial impression is that this shouldn't be a separate `.next.toml` since we can make changes that affect both the client and the server, and we shouldn't have to copy/paste entries into both files to represent those. Also, GitHub can only have one set of notes for a release, so these really should be combined.

I think we can just add a property to the current changelog toml format that indicates the change is for client, server, or both. Then we can just modify how we render the changelog so that it breaks out separate client/server sections.

2022-06-28 09:50 UTC, crisidev requested changes

2022-06-28 09:50 UTC, crisidev commented on codegen-server/SERVER_CHANGELOG.md
> +- 🎉 ([smithy-rs#1454](https://github.com/awslabs/smithy-rs/issues/1454)) Python can be used for writing business logic, executing on top of smithy-rs Rust runtime
This PR is not related to Python, I think you made a mistake linking it. It should be https://github.com/awslabs/smithy-rs/pull/1403

On top of this, the wording of the description is not 100% correct as until https://github.com/awslabs/smithy-rs/pull/1476 is not merged, the Python system is not usable. 

I would reword it like: `Initial support to code-generate support to write the business logic in Python, executing on top of Rust. This PR introduce code-generation of operations and simple shapes (Structure and Enum) and add runtime support to start the Hyper server from Python, but does not generate an importable shared library yet.`

2022-08-02 20:38 UTC, crisidev commented
Is this PR still relevant?

2022-08-02 20:41 UTC, closed without merging

2022-08-02 20:44 UTC, drganjoo commented
This PR is no longer needed as changelog tool has now been updated to include server SDK changes.