Add TLS support to Pokemon server
awslabs/smithy-rs pull request #1634
Opened 2022-08-15 11:40 UTC by unexge

## Motivation and Context
This PR adds TLS support to Pokemon server. We can refer Pokemon server from our docs to show our users how to configure TLS for their own services. It also addresses https://github.com/awslabs/smithy-rs/issues/1542 because without TLS and necessary configuration, by default clients don't negotiate their way up to http2.

## Description
This PR adds TLS support to Pokemon server using [tls-listener](https://crates.io/crates/tls-listener) and [tokio-rustls](https://crates.io/crates/tokio-rustls) (and [rustls-pemfile](https://crates.io/crates/rustls-pemfile) to parse PEM files). It can be enabled via `--use-tls` and can be configured with `--tls-cert-path` and `--tls-key-path` flags.

## Testing
It can be tested by creating test certificates and making requests via cURL to make sure it works as expected.

```bash
$ cd rust-runtime/aws-smithy-http-server/examples/pokemon-service
# Create test certificates for localhost, it will create "./localhost.pem" and "./localhost-key.pem" in same directory
$ mkcert localhost 
# Run Pokemon service with TLS enabled using generated certificates
$ cargo run -- --use-tls --tls-cert-path ./localhost.pem --tls-key-path ./localhost-key.pem
```

```bash
# In different terminal make request to Pokemon service with https
$ curl -D- -H "Accept: application/json" https://localhost:13734/pokemon-species/pikachu
HTTP/2 200
content-type: application/json
content-length: 573
date: Mon, 15 Aug 2022 11:38:54 GMT

{"flavorTextEntries":[{"flavorText":"When several of these Pokémon gather, their electricity could build and cause lightning storms.","language":"en"},{"flavorText":"Cuando varios de estos Pokémon se juntan, su energía puede causar fuertes tormentas.","language":"es"},{"flavorText":"Quando vari Pokémon di questo tipo si radunano, la loro energia può causare forti tempeste.","language":"it"},{"flavorText":"ほっぺたの りょうがわに ちいさい でんきぶくろを もつ。ピンチのときに ほうでんする。","language":"jp"}],"name":"pikachu"}
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-08-15 15:34 UTC, weihanglo reviewed
I find the PR really great! However, in my macbook if there is a Unknown CA or corrupted TLS data, the server just goes down. Do we need to handle this?

2022-08-15 15:35 UTC, weihanglo commented
BTW, `curl -k` can bypass the unknown CA issue.

2022-08-15 16:34 UTC, unexge commented
Good catch! I was using `mkcert -install` to have trusted local CA and missed that error. I'm not sure how to handle unknown CAs or corrupted TLS data but the server shouldn't stop at least

2022-08-16 11:43 UTC, weihanglo approved these changes
LGTM now. Thanks for fixing the crashing issue 👍🏾

2022-08-16 12:03 UTC, david-perez requested changes
Content looks good. However, I'd prefer it if we put this TLS example in a separate executable [using `[[bin]]`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target). I expect most service owners to use a separate process (possibly in another host) to do TLS termination. This way we keep the main example for most users copy-pasteable. That executable could be documented with your investigation regarding h2 negotiation you've written in the PR description, which is also valuable.

Bonus points: it'd be nice if the new executable could have integration tests with the Pokémon Smithy client using HTTPS, perhaps asserting that HTTP2 is used too?

2022-08-17 17:53 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/Cargo.toml
> +# This dependencies only required for `pokemon-service-tls`
```suggestion
# These dependencies are only required for `pokemon-service-tls`.
```

2022-08-17 17:53 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/Cargo.toml
> +# This dependencies only required for testing `pokemon-service-tls`
```suggestion
# These dependencies are only required for testing `pokemon-service-tls`.
```

2022-08-17 17:53 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/src/bin/pokemon-service-tls.rs
> +// flag while making requests with cURL or you can run `$ mkcert -install` to trust certificates created by `mkcert`.
```suggestion
// flag while making requests with cURL or you can run `mkcert -install` to trust certificates created by `mkcert`.
```

2022-08-17 17:53 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/src/bin/pokemon-service-tls.rs
> +// You can use `mkcert` to create certificates for testing:
I'd link somewhere to https://github.com/FiloSottile/mkcert.

2022-08-17 17:53 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/tests/helpers.rs
> +        .middleware_fn(move |mut req| {
This closure could now be extracted to its own function, since both the HTTP client and HTTPs client builders use it.

2022-08-18 11:19 UTC, david-perez commented on rust-runtime/aws-smithy-http-server/examples/pokemon-service/tests/helpers.rs
> +}
```suggestion
fn rewrite_base_url(base_url: String) -> Request {
    let http_req = req.http_mut();
    let uri = format!("{base_url}{}", http_req.uri().path());
    *http_req.uri_mut() = uri.parse().unwrap();
    req
}
```

This should work too.

2022-08-18 11:30 UTC, david-perez approved these changes

2022-08-18 11:32 UTC, merged