Nested server structure member shapes targeting simple shapes with default trait
awslabs/smithy-rs pull request #2352
Opened 2023-02-13 14:09 UTC by 82marbag

Closes: #2343 

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2023-02-15 12:26 UTC, david-perez requested changes
Fix looks good, but we need tests so that we don't regress on this.

We need _at least_ a regular integration test / Kotlin unit test using `serverIntegrationTest` testing a minimal version of the model in https://github.com/awslabs/smithy-rs/issues/2343.

We should add a test to `ConstraintsTest` to test that indeed `@default` is now not detected as constrained on a simple shape too.

2023-02-15 12:26 UTC, david-perez commented on CHANGELOG.next.toml
> +message = "Mark unconstrained structures with optional _or_ default members."
This message is not useful to users at all. It makes no mention of the bug itself.

How about something like "Fix bug whereby nested server structure member shapes targeting simple shapes with `@default` produced Rust code that did not compile"?

2023-02-15 12:26 UTC, david-perez commented on CHANGELOG.next.toml
> +references = ["smithy-rs#2352"]
Reference the issue too: https://github.com/awslabs/smithy-rs/issues/2343.

2023-02-17 17:11 UTC, 82marbag commented
Tests have been added

2023-02-17 17:21 UTC, david-perez approved these changes

2023-02-17 17:21 UTC, david-perez commented on codegen-server/src/test/kotlin/software/amazon/smithy/rust/codegen/server/smithy/ConstraintsTest.kt
> +        structWithInnerDefault.canReachConstrainedShape(model, symbolProvider) shouldBe false
I would call `isDirectlyConstrained` on `StructWithInnerDefault$PrimitiveBoolean` too, to make the unit tests be more unit-like.

2023-02-17 17:21 UTC, david-perez commented on codegen-server/src/test/kotlin/software/amazon/smithy/rust/codegen/server/smithy/generators/ServerBuilderConstraintViolationsTest.kt
> +        val model = """
Nice. I'd leave a comment linking to https://github.com/awslabs/smithy-rs/issues/2343 so the reader can easily find how this test came to be.

In general I like how the Rust compiler adds test for reported issues and links back to the info on GitHub e.g. https://github.com/rust-lang/rust/tree/master/tests/ui/codegen

2023-02-17 18:45 UTC, merged