Python: Event Streaming
awslabs/smithy-rs pull request #2482
Opened 2023-03-21 15:48 UTC by unexge

## Motivation and Context
Closes https://github.com/awslabs/smithy-rs/issues/1752

## Description

## Testing

## TODOs
- [ ] Update PyO3 and PyO3Asyncio to latest

## Checklist

- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [ ] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2023-03-21 16:10 UTC, crisidev requested changes
Somehow the codegen diff is showning this PR is reverting to an older version of tokio that is affected by a CVE and @rcoh fixed a couple of days ago: https://github.com/awslabs/smithy-rs/pull/2474

2023-03-31 16:02 UTC, unexge commented on codegen-server/python/src/main/kotlin/software/amazon/smithy/rust/codegen/server/python/smithy/generators/PythonServerEventStreamWrapperGenerator.kt
> +    private val parkingLot = PythonServerCargoDependency.ParkingLot.toType()
Let's create an issue to whether we can switch to `std::sync::Mutex` instead of `parking_lot::Mutex`

2023-03-31 16:06 UTC, unexge commented on codegen-server/python/src/main/kotlin/software/amazon/smithy/rust/codegen/server/python/smithy/generators/PythonServerEventStreamWrapperGenerator.kt
> +                    let inner = inner.take().expect("stream is already gone");
Let's be more explicit here and give some details about what went wrong

2023-04-10 12:46 UTC, unexge commented on codegen-server/python/src/main/kotlin/software/amazon/smithy/rust/codegen/server/python/smithy/generators/PythonServerEventStreamWrapperGenerator.kt
> +                    #{PyO3}::exceptions::PyAttributeError::new_err("this is a write-only object").into_py(py)
`mypy` only supports read-only fields by adding `@property` to the field but nothing for write-only fields.

2023-04-10 15:13 UTC, Velfi approved these changes

2023-04-11 10:55 UTC, crisidev approved these changes
LGTM!

2023-04-11 11:50 UTC, merged