Omit fractional seconds from `date-time` format
awslabs/smithy-rs pull request #2989
Opened 2023-09-18 18:48 UTC by rschmitt

## Motivation and Context
Closes #2831.

## Description
Fractional seconds will still be accepted during parsing, but not emitted during serialization.

## Testing
```
./gradlew codegen-core:check codegen-client:check codegen-server:check codegen-client-test:check codegen-server-test:check
```

## Checklist
- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

2023-09-19 13:55 UTC, rcoh commented
doesn't need to be in this PR, but we should also add an [S3-specific protocol test](
https://github.com/awslabs/smithy-rs/blob/main/aws/sdk/aws-models/s3-tests.smithy) for https://github.com/awslabs/aws-sdk-rust/issues/818

Can you also link to aws-sdk-rust#818 from the changelog?

It would be good to also verify that that API actually works after this change.

We should also contribute a protocol test upstream that mandates this behavior—currently there are non that I'm aware of.

2023-09-19 13:55 UTC, rcoh approved these changes

2023-09-20 00:02 UTC, jdisanti reviewed
I think you have the wrong date format. This change should be applied to `http-date` rather than `date-time`. We definitely want fractional seconds on date-time.

2023-09-20 13:19 UTC, rcoh requested changes
Wow, good catch all on the HTTP Date, glad we actually tested the end-bug. I think we need to back out the changes to the RFC3339 serializer than we're g2g

2023-09-20 13:19 UTC, rcoh commented on CHANGELOG.next.toml
> +message = "Omit fractional seconds from `date-time` format."
```suggestion
message = "Omit fractional seconds from `http-date` format."
```

2023-09-20 13:19 UTC, rcoh commented on rust-runtime/aws-smithy-json/src/serialize.rs
> +            r#"{"epoch_seconds":5.2,"date_time":"2021-05-24T15:34:50Z","http_date":"Wed, 21 Oct 2015 07:28:00 GMT"}"#,
We should change this test to put a fraction in http_date—and I think we need to back out the changes to date_time, only http_date omits the subsecond. My bad on that—good catch from @jdisanti

2023-09-20 13:19 UTC, rcoh commented on rust-runtime/aws-smithy-types/src/date_time/format.rs
> -    }
We need to bring this back—sorry about that

2023-09-21 19:16 UTC, merged