Updated SageMaker examples to take a region arg; added doc comments.
awslabs/smithy-rs pull request #524
Opened 2021-06-21 19:20 UTC by Doug-AWS

*Issue #, if available:*
SageMaker code examples had no doc comments.

*Description of changes:*
Added them and an optional command-line region arg (-d DEFAULT-REGION).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-06-21 19:58 UTC, jdisanti requested changes

2021-06-21 19:58 UTC, jdisanti commented on aws/sdk/examples/sagemaker/src/bin/list-training-jobs.rs
> +        println!("{}", deets);
You can combine these two lines:
```
println!(
    "{}\t{}\t{}\t{:#?}",
    name,
    ...
);
```

2021-06-21 19:58 UTC, jdisanti commented on aws/sdk/examples/sagemaker/src/bin/sagemaker-helloworld.rs
> +        println!("{}", details);
Likewise here

2021-06-22 12:27 UTC, Doug-AWS commented on aws/sdk/examples/sagemaker/src/bin/list-training-jobs.rs
> +        println!("{}", deets);
Updated, thanks.

2021-06-22 12:27 UTC, Doug-AWS commented on aws/sdk/examples/sagemaker/src/bin/sagemaker-helloworld.rs
> +        println!("{}", details);
Done.

2021-06-22 16:49 UTC, jdisanti approved these changes

2021-06-22 18:30 UTC, merged