Added AutoScaling code examples
awslabs/smithy-rs pull request #576
Opened 2021-07-02 17:20 UTC by Doug-AWS

*Issue #, if available:*

*Description of changes:*
Added list-autoscaling-groups, create-autoscaling-group, update-autscaling-group, and delete-autoscaling-group.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-07-02 17:26 UTC, jdisanti requested changes

2021-07-02 17:26 UTC, jdisanti commented on aws/sdk/examples/autoscaling/src/bin/create-autoscaling-group.rs
> +    let region = region
Take a look at the [cognitoidentity](https://github.com/awslabs/smithy-rs/blob/main/aws/sdk/examples/cognitoidentity/src/bin/list-identity-pools.rs#L38-L48) example for how we should be acquiring the region now. We now have a region ChainProvider that simplifies it.

2021-07-02 17:26 UTC, jdisanti commented on aws/sdk/examples/autoscaling/src/bin/delete-autoscaling-group.rs
> +    }
This can be simplified to:
```rust
let f = force.then(|| true);
```

2021-07-02 17:35 UTC, rcoh commented on aws/sdk/examples/autoscaling/src/bin/delete-autoscaling-group.rs
> +    }
```suggestion
    let f = force.then(|| true)
```

2021-07-06 23:26 UTC, jdisanti approved these changes

2021-07-06 23:27 UTC, merged